version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    platform: linux/arm64/v8
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    platform: linux/arm64/v8
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    container_name: php

  mysql:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  phpmyadmin:
    image: arm64v8/phpmyadmin:5.2.1
    platform: linux/arm64/v8
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    depends_on:
      - mysql
    ports:
      - "8080:80"

volumes:
  db_data: